### Obter todos os contactos (Local)
GET http://localhost:8080/contacts

### Criar novo contacto (Local)
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Ana",
  "lastName": "Silva",
  "email": "ana.silva@test.com",
  "favoriteColor": "Azul",
  "birthday": "1995-04-12"
}

### Atualizar contacto (Local - substitua pelo ID retornado no POST)
PUT http://localhost:8080/contacts/<ID_DO_CONTACTO> HTTP/1.1
content-type: application/json

{
  "firstName": "Ana",
  "lastName": "Santos",
  "email": "ana.santos@test.com",
  "favoriteColor": "Verde",
  "birthday": "1995-04-12"
}

### Apagar contacto (Local)
DELETE http://localhost:8080/contacts/<ID_DO_CONTACTO> HTTP/1.1